name: cbs_create
description: For creating custom flutter project from CBS Architecture
version: 1.0.1
homepage: https://github.com/webdastur/cbs_create

environment:
  sdk: '>=2.7.0 <3.0.0'


executables:
  cbs_create:

dependencies:
 path: ^1.6.4
 rename: ^1.1.9
  
 args: ^1.5.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
 
