name: cbs_create
description: For creating custom flutter project from CBS Architecture. CBS Architecture https://github.com/webdastur/cbs_architecture
version: 1.0.3
homepage: https://github.com/webdastur/cbs_create

environment:
  sdk: '>=2.7.0 <3.0.0'


executables:
  cbs_create:

dependencies:
 path: ^1.8.0
 rename: ^1.3.0
  
 args: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
 
